Models/Item.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Inventory_Management_iTransition.Models
{
	public class Item
	{
		[Key]
		public int Id { get; set; }
        [Required]
        [StringLength(255)]
        [Index("IX_Inventory_CustomId", 2, IsUnique = true)]
        public string CustomId { get; set; }

        [Required]
        [Index("IX_Inventory_CustomId", 1, IsUnique = true)]
        public int InventoryId { get; set; }

        [ForeignKey("InventoryId")]
        public virtual Inventory Inventory { get; set; }

        [Required]
        public string CreatedById { get; set; }

        [ForeignKey("CreatedById")]
        public virtual ApplicationUser CreatedBy { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        [Timestamp]
        public byte[] RowVersion { get; set; }

        public virtual ICollection<CustomFieldValue> CustomFieldValues { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public int? SequenceNumber { get; set; }

        public Item()
        {
            CustomFieldValues = new HashSet<CustomFieldValue>();
            Likes = new HashSet<Like>();
        }
    }
}

Controllers/ItemController.cs
using Inventory_Management_iTransition.Context;
using Inventory_Management_iTransition.Models;
using Inventory_Management_iTransition.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Inventory_Management_iTransition.Services;

namespace Inventory_Management_iTransition.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {
        private InMContext db;
        private readonly IdFormatService _idFormatService;

        public ItemController()
        {
            db = new InMContext();
            _idFormatService = new IdFormatService();
        }

        [AllowAnonymous]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var item = await db.Items
                .Include(i => i.Inventory)
                .Include(i => i.CreatedBy)
                .Include(i => i.Likes)
                .Include(i => i.CustomFieldValues.Select(cfv => cfv.CustomField))
                .FirstOrDefaultAsync(i => i.Id == id);

            if (item == null)
            {
                return HttpNotFound();
            }

            return View(item);
        }


        public async Task<ActionResult> Create(int inventoryId)
        {
            var inventory = await db.Inventories
                .Include(i => i.CustomFields)
                .FirstOrDefaultAsync(i => i.Id == inventoryId);

            if (inventory == null)
            {
                return HttpNotFound();
            }

            var viewModel = new ItemFormViewModel
            {
                InventoryId = inventory.Id,
                InventoryTitle = inventory.Title,
                FieldValues = inventory.CustomFields.Select(cf => new CustomFieldValueViewModel
                {
                    CustomFieldId = cf.Id,
                    FieldName = cf.Title,
                    FieldType = cf.Type
                }).ToList()
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ItemFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                var inventoryForForm = await db.Inventories.Include(i => i.CustomFields).FirstOrDefaultAsync(i => i.Id == viewModel.InventoryId);
                viewModel.InventoryTitle = inventoryForForm.Title;
                viewModel.FieldValues = inventoryForForm.CustomFields.Select(cf => new CustomFieldValueViewModel
                {
                    CustomFieldId = cf.Id,
                    FieldName = cf.Title,
                    FieldType = cf.Type
                }).ToList();
                return View(viewModel);
            }

            var inventory = await db.Inventories.Include(i => i.CustomIdElements).FirstOrDefaultAsync(i => i.Id == viewModel.InventoryId);
            if (inventory == null)
            {
                return HttpNotFound();
            }

            var userId = User.Identity.GetUserId();
            if (inventory.OwnerId != userId && !User.IsInRole("Admin") &&
                !await db.InventoryUserAccesses.AnyAsync(a => a.InventoryId == viewModel.InventoryId && a.UserId == userId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "You don't have permission to add items to this inventory.");
            }

            var newItem = new Item
            {
                InventoryId = viewModel.InventoryId,
                CreatedById = userId,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow,
            };

            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    if (inventory.CustomIdElements.Any(e => e.Type == IdElementType.Sequence))
                    {
                        var maxSeq = await db.Items
                            .Where(i => i.InventoryId == inventory.Id)
                            .Select(i => (int?)i.SequenceNumber)
                            .DefaultIfEmpty(0)
                            .MaxAsync();
                        newItem.SequenceNumber = (maxSeq ?? 0) + 1;
                    }

                    for (int i = 0; i < 5; i++)
                    {
                        var generatedId = await _idFormatService.GenerateIdAsync(inventory, db);
                        var isDuplicate = await db.Items.AnyAsync(it => it.InventoryId == viewModel.InventoryId && it.CustomId == generatedId);

                        if (!isDuplicate)
                        {
                            newItem.CustomId = generatedId;
                            break;
                        }
                    }

                    if (string.IsNullOrEmpty(newItem.CustomId))
                    {
                        ModelState.AddModelError("", "Could not generate a unique item ID. Please try again.");
                        var inventoryForForm = await db.Inventories.Include(i => i.CustomFields).FirstOrDefaultAsync(i => i.Id == viewModel.InventoryId);
                        viewModel.InventoryTitle = inventoryForForm.Title;
                        viewModel.FieldValues = inventoryForForm.CustomFields.Select(cf => new CustomFieldValueViewModel
                        {
                            CustomFieldId = cf.Id,
                            FieldName = cf.Title,
                            FieldType = cf.Type
                        }).ToList();
                        return View(viewModel);
                    }

                    db.Items.Add(newItem);
                    await db.SaveChangesAsync();

                    if (viewModel.FieldValues != null)
                    {
                        foreach (var fieldValueModel in viewModel.FieldValues)
                        {
                            var customFieldValue = new CustomFieldValue
                            {
                                ItemId = newItem.Id,
                                CustomFieldId = fieldValueModel.CustomFieldId,
                                Value = fieldValueModel.Value ?? (fieldValueModel.FieldType == FieldType.Checkbox ? "false" : "")
                            };
                            db.CustomFieldValues.Add(customFieldValue);
                        }
                        await db.SaveChangesAsync();
                    }

                    transaction.Commit();
                    return RedirectToAction("Details", "Inventory", new { id = viewModel.InventoryId });
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    ModelState.AddModelError("", "An error occurred while saving the item: " + ex.Message);
                    var inventoryForForm = await db.Inventories.Include(i => i.CustomFields).FirstOrDefaultAsync(i => i.Id == viewModel.InventoryId);
                    viewModel.InventoryTitle = inventoryForForm.Title;
                    viewModel.FieldValues = inventoryForForm.CustomFields.Select(cf => new CustomFieldValueViewModel
                    {
                        CustomFieldId = cf.Id,
                        FieldName = cf.Title,
                        FieldType = cf.Type
                    }).ToList();
                    return View(viewModel);
                }
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteMultiple(IEnumerable<int> itemIds, int inventoryId)
        {
            if (itemIds != null && itemIds.Any())
            {
                var itemsToDelete = await db.Items
                    .Where(i => itemIds.Contains(i.Id) && i.InventoryId == inventoryId)
                    .ToListAsync();

                var inventory = await db.Inventories.FindAsync(inventoryId);
                var currentUserId = User.Identity.GetUserId();
                if (inventory.OwnerId != currentUserId && !User.IsInRole("Admin"))
                {
                    return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
                }

                db.Items.RemoveRange(itemsToDelete);
                await db.SaveChangesAsync();
            }

            return RedirectToAction("Details", "Inventory", new { id = inventoryId });
        }
    }
}

Controllers/LikeController.cs
using Inventory_Management_iTransition.Context;
using Inventory_Management_iTransition.Models;
using Inventory_Management_iTransition.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Inventory_Management_iTransition.Controllers
{
    [Authorize]
    public class LikeController : Controller
    {
        private InMContext db;

        public LikeController()
        {
            db = new InMContext();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Toggle(int itemId)
        {
            var userId = User.Identity.GetUserId();
            var existingLike = await db.Likes
                .FirstOrDefaultAsync(l => l.ItemId == itemId && l.UserId == userId);

            if (existingLike != null)
            {
                db.Likes.Remove(existingLike);
            }
            else
            {
                var newLike = new Like
                {
                    ItemId = itemId,
                    UserId = userId
                };
                db.Likes.Add(newLike);
            }

            await db.SaveChangesAsync();

            var likeCount = await db.Likes.CountAsync(l => l.ItemId == itemId);

            return Json(new LikeViewModel { NewLikeCount = likeCount });
        }
    }
}

Views/Item/Create.cshtml
@model Inventory_Management_iTransition.ViewModel.ItemFormViewModel
@{
    ViewBag.Title = "Create New Item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h4>Add New Item to @Model.InventoryTitle</h4>
                </div>
                <div class="card-body">
                    <p>Fill out the details for your new item below.</p>
                    <hr />

                    @using (Html.BeginForm("Create", "Item", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(m => m.InventoryId)

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        for (int i = 0; i < Model.FieldValues.Count; i++)
                        {
                            <div class="form-group mb-3">
                                @Html.LabelFor(m => m.FieldValues[i].Value, Model.FieldValues[i].FieldName, new { @class = "form-label" })
                                @Html.HiddenFor(m => m.FieldValues[i].CustomFieldId)
                                @Html.HiddenFor(m => m.FieldValues[i].FieldName)
                                @Html.HiddenFor(m => m.FieldValues[i].FieldType)

                                @switch (Model.FieldValues[i].FieldType)
                                {
                                    case Inventory_Management_iTransition.Models.FieldType.MultiLineText:
                                        @Html.TextAreaFor(m => m.FieldValues[i].Value, 5, 1, new { @class = "form-control" })
                                        break;
                                    case Inventory_Management_iTransition.Models.FieldType.Checkbox:
                                        <div class="form-check pt-2">
                                            @Html.CheckBox(string.Format("FieldValues[{0}].Value", i), false, new { @class = "form-check-input", value = "true" })
                                            <input type="hidden" name="@string.Format("FieldValues[{0}].Value", i)" value="false" />
                                        </div>
                                        break;
                                    case Inventory_Management_iTransition.Models.FieldType.Numeric:
                                        @Html.TextBoxFor(m => m.FieldValues[i].Value, new { @class = "form-control", type = "number" })
                                        break;
                                    case Inventory_Management_iTransition.Models.FieldType.DocumentLink:
                                        @Html.TextBoxFor(m => m.FieldValues[i].Value, new { @class = "form-control", type = "url" })
                                        break;
                                    default: 
                                        @Html.TextBoxFor(m => m.FieldValues[i].Value, new { @class = "form-control" })
                                        break;
                                }
                                @Html.ValidationMessageFor(m => m.FieldValues[i].Value, "", new { @class = "text-danger" })
                            </div>
                        }

                        <hr />
                        <div class="d-flex justify-content-end">
                            @Html.ActionLink("Cancel", "Details", "Inventory", new { id = Model.InventoryId }, new { @class = "btn btn-secondary me-2" })
                            <input type="submit" value="Create Item" class="btn btn-primary" />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

Views/Item/Details.cshtml
@model Inventory_Management_iTransition.Models.Item
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Item Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var currentUserId = User.Identity.GetUserId();
    var hasLiked = Model.Likes.Any(l => l.UserId == currentUserId);
}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <div>
                        <h4 class="mb-0">Item: @Model.CustomId</h4>
                        <small class="text-muted">In Inventory: @Html.ActionLink(Model.Inventory.Title, "Details", "Inventory", new { id = Model.InventoryId }, null)</small>
                    </div>
                    <div>
                        <!-- Like Button and Count -->
                        @using (Html.BeginForm("Toggle", "Like", FormMethod.Post, new { id = "like-form", @class = "d-inline" }))
                        {
                            @Html.AntiForgeryToken()
                            @Html.Hidden("itemId", Model.Id)
                            <button type="submit" class="btn @(hasLiked ? "btn-danger" : "btn-outline-danger")">
                                <i class="fas fa-heart"></i>
                                <span id="like-count">@Model.Likes.Count()</span>
                            </button>
                        }
                    </div>
                </div>
                <div class="card-body">
                    <dl class="row">
                        <dt class="col-sm-4">Created By</dt>
                        <dd class="col-sm-8">@Model.CreatedBy.UserName</dd>

                        <dt class="col-sm-4">Created Date</dt>
                        <dd class="col-sm-8">@Model.CreatedAt.ToString("g")</dd>

                        <dt class="col-sm-4">Last Updated</dt>
                        <dd class="col-sm-8">@Model.UpdatedAt.ToString("g")</dd>
                    </dl>
                    <hr />
                    <h5>Custom Fields</h5>
                    @if (Model.CustomFieldValues.Any())
                    {
                        <dl class="row">
                            @foreach (var fieldValue in Model.CustomFieldValues)
                            {
                                <dt class="col-sm-4">@fieldValue.CustomField.Title</dt>
                                <dd class="col-sm-8">
                                    @if (fieldValue.CustomField.Type == Inventory_Management_iTransition.Models.FieldType.Checkbox)
                                    {
                                        <span>@(fieldValue.Value == "true" ? "Yes" : "No")</span>
                                    }
                                    else
                                    {
                                        <span>@fieldValue.Value</span>
                                    }
                                </dd>
                            }
                        </dl>
                    }
                    else
                    {
                        <p class="text-muted">This item has no custom field data.</p>
                    }
                </div>
                <div class="card-footer text-end">
                    @Html.ActionLink("Back to Inventory", "Details", "Inventory", new { id = Model.InventoryId }, new { @class = "btn btn-secondary" })
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#like-form').on('submit', function (e) {
                e.preventDefault();
                var form = $(this);
                var button = form.find('button');
                var likeCountSpan = $('#like-count');

                $.ajax({
                    url: form.attr('action'),
                    type: form.attr('method'),
                    data: form.serialize(),
                    success: function (response) {
                        likeCountSpan.text(response.NewLikeCount);

                        // Toggle the button's appearance
                        if (button.hasClass('btn-danger')) {
                            button.removeClass('btn-danger').addClass('btn-outline-danger');
                        } else {
                            button.removeClass('btn-outline-danger').addClass('btn-danger');
                        }
                    },
                    error: function () {
                        alert('An error occurred while liking the item.');
                    }
                });
            });
        });
    </script>
}